project:
  type: seedcase-theme

website:
  title: "Seedcase Soil"
  site-url: "https://soil.seedcase-project.org"
  repo-url: "https://github.com/seedcase-project/seedcase-soil"
  page-navigation: true
  navbar:
    pinned: true
    title: false
    logo: "_extensions/seedcase-project/seedcase-theme/logos/seedcase/icon.svg"
    logo-alt: "seedcase-soil logo: Main page"
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Reference"
        href: docs/reference/index.qmd
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/seedcase-soil"
        aria-label: "GitHub icon: Source code"
      - icon: house
        href: "https://seedcase-project.org"
        aria-label: "House icon: Main website for the Seedcase Project"
  sidebar:
    - id: overview
      pinned: true
      style: "floating"
      contents:
        - text: "Overview"
          href: index.qmd
        - CHANGELOG.md
        - CONTRIBUTING.md

quartodoc:
  sidebar: "docs/reference/_sidebar.yml"
  style: "pkgdown"
  dir: "docs/reference"
  package: "seedcase_soil"
  parser: google
  dynamic: true
  renderer:
    style: _renderer.py
    table_style: description-list
    show_signature_annotations: true
  sections:
    - title: "CLI helpers"
      desc: "Functionality that make our CLI apps more user-friendly, both in terms of appearance and behavior."
      contents:
        - "pretty_print"
        - "print_if_verbose"
        - "run_without_tracebacks"
        - "setup_cli"
    - title: "Example Data Packages"
      desc: "Class to access example data packages that we use for testing and demonstration purposes."
      contents:
        - "Example"
    - title: "Functional programming"
      desc: "Functions that support a functional programming style."
      contents:
        - "keep"
        - "fmap"
        - "flat_fmap"
        - "pairwise_fmap"
    - title: "Reading Data Package properties"
      desc: "Functionality for reading properties from Data Packages."
      contents:
        - "Address"
        - "parse_source"
        - "read_properties"
        - "write_properties"
    - title: "Documentation helpers"
      desc: "Functionality that helps with creating our documentation."
      contents:
        - "format_output_for_docs"

metadata-files:
  - docs/reference/_sidebar.yml

format:
  seedcase-theme-html:
    include-before-body:
      - "docs/includes/site-counter.html"
